docker:
  image: "maven:3-jdk-8"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
merge:
  commanders:
    - albogdano
    - lucav
  script: mvn clean install
release:
  commanders:
    - albogdano
    - lucav
  script: |
    echo "releasing ${tag}..."
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Prelease --settings /home/r/settings.xml