language: java
jdk:
  - oraclejdk8
after_success:
  - mvn clean verify
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04820972e9b664f3140c
    on_success: change
    on_failure: always
    on_start: never
    