language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - jdk_switcher use oraclejdk8
  - mvn clean install sonar:sonar
addons:
  sonarcloud:
    organization: "erudika"
    token:
      secure: "Y/RKxv18CIQUdzIP62vEV66FRuFf6Zx+iCRQ7/7Rh+R5kEiN0eiY6ckh0MVtoF9ZDOqDDVGvhFdX6Fnzk8+nA7wW3MoTgCZaSLB9gr5W2sRA+HQrT2Kd+e1VLnhYupYtlNRye79SrjX843EqIxwVzKTWGx++uoE0zmZptVsS05RQyySJ0YSzkUJud990fF9UfOkG87G1MTOTwLFQUUYNe3Q1+CaXStPv5vFf4OI9691SxpRX9We9ldT4LSnAsN6ssayUe3LG//JRwDOg+jKMcWxzQNbdTBCn6ticzyNzgp8/w+lUOm81pqvdssj6lcE2fXRmrl+P949tY4bqA/XqNDmC7Z0F2+TRemNdLQKAPCcqf+UV2udZ194U7oKdw0GIOzPTdAMBpYsQOz7dylI+tdiyBd53AtCx9ClfAPTjwbTrS1r2P3hk5KY8TK7mvuB2SinLHSEKmJJsaFIOxX/RWTLsogFgXktcZ+uF7QcHkSZmS01UWit102EkCRekuYENnCQc3UoFMu6J7wnIBahtB3P5+3LIahxWsDjQru8CT9XmIXeYoTr/upUn4POZgmyMWT/d6ct9bKJNsoAimQH8vZ3rclnlqKFILPPTtSGa30ypmUcaM0kqsEomOKut2qlRFIORaopHiFD+qBcYayGKywP+3DM8t9mYjO5uPJyALuw="
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04820972e9b664f3140c
    on_success: change
    on_failure: always
    on_start: never
    
